# Generated by Django 4.1.6 on 2023-02-10 03:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('timeCreate', models.DateTimeField(auto_now_add=True)),
                ('cpf', models.IntegerField(blank=True, default=0)),
                ('picture', models.ImageField(upload_to='uploads', verbose_name='Imagem')),
                ('age', models.IntegerField(default=0, verbose_name='Idade')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Avaliação')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Saldo')),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('brand', models.CharField(max_length=100, verbose_name='Marca')),
                ('color', models.CharField(max_length=100, verbose_name='Cor')),
                ('year', models.IntegerField(verbose_name='Ano')),
                ('picture_moto', models.ImageField(upload_to='uploads', verbose_name='Imagem')),
            ],
        ),
        migrations.CreateModel(
            name='MotoTaxi',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('timeCreate', models.DateTimeField(auto_now_add=True)),
                ('cpf', models.IntegerField(blank=True, default=0)),
                ('picture', models.ImageField(upload_to='uploads', verbose_name='Imagem')),
                ('age', models.IntegerField(default=0, verbose_name='Idade')),
                ('rate', models.IntegerField(blank=True, null=True, verbose_name='Avaliação')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Saldo')),
                ('cnh', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Valor')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Distância')),
                ('start', models.CharField(max_length=300, verbose_name='Começo')),
                ('end', models.CharField(max_length=300, verbose_name='Chegada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Site.client', verbose_name='Cliente')),
                ('motoTax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Site.mototaxi', verbose_name='Moto Taxi')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('text', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Nota')),
                ('owner', models.CharField(blank=True, max_length=150, verbose_name='Autor')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Site.client', verbose_name='Cliente')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.mototaxi', verbose_name='Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='mototaxi',
            name='history',
            field=models.ManyToManyField(blank=True, to='Site.ride', verbose_name='Historico'),
        ),
        migrations.AddField(
            model_name='mototaxi',
            name='motorcycle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Site.motorcycle', verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='client',
            name='Favorite',
            field=models.ManyToManyField(blank=True, to='Site.mototaxi', verbose_name='Favoritos'),
        ),
        migrations.AddField(
            model_name='client',
            name='history',
            field=models.ManyToManyField(blank=True, to='Site.ride', verbose_name='Historico'),
        ),
    ]
