# Generated by Django 4.1.6 on 2023-02-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_ride_status_alter_ride_mototax'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
